config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  resources :tasks
  resources :projects
  root to: 'dashboards#show'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'users/sign_in', to: 'users/sessions#new', as: :new_admin_session
    get 'users/sign_out', to: 'users/sessions#destroy', as: :destroy_admin_session
  end

  # devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
	has_many :tasks
	def self.get_by_status(status)
        self.all.select do |project|
            project.status == status
        end
    end

    def update_status
        if self.tasks == []
            self.status = "Empty"
        elsif self.tasks.any?{|task| task.status == "Pending"}
            self.status = "Pending"
        else
            self.status = "Completed"
        end
        self.save
    end

    def tasks_by_status(status)
        self.tasks.select do |task|
            task.status == status
        end
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def index
        @backlog_projects = Project.get_by_status("Backlog")
        @inprogress_projects = Project.get_by_status("In-progress")
        @done_projects = Project.get_by_status("Done")
    end

    def new
        @project = Project.new
    end

    def create
        @project = Project.create(project_params(:name, :description))
        @project.status = "Backlog"
        @project.save
        redirect_to project_path(@project)
    end

    def show
        @project = Project.find(params[:id])
    end

    def edit
        @project = Project.find(params[:id])
    end

    def update
        @project = Project.find(params[:id])
        @project.update(project_params(:name, :description))
        @project.update_status
        redirect_to project_path(@project)
    end

    def destroy
        @project = Project.find(params[:id]).destroy
        redirect_to projects_path
    end

    private
    def project_params(*args)
        params.require(:project).permit(*args)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/edit.html.erb
<h1><%= "EDIT: " + @project.name %></h1>

<%= form_for(@project) do |f| %>
    <%= f.label :name%><br>
    <%= f.text_field :name%><br>
    <br><%= f.label :description%><br>
    <%= f.text_area :description%><br>
    <br><%= f.submit %><br>
<% end %>

<br><%= button_to "Delete project", @project, :method => :delete, data: {confirm: 'Are you sure?'} %>

app/views/projects/index.html.erb
<div class="media-body">
<table class="table table-hover" >
    <h1>PROJECTS LIST</h1>
    <%= button_to "Create Project", new_project_path, method: :get %>
    <thead>
      <tr>
        <th>Backlog projects</th>
        <th>Pending projects</th>
        <th>Done projects</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
            <% @backlog_projects.each do |project| %>
              <%= link_to project.name, project_path(project) %>
            <% end %>     
         </td>
        <td>
            <% @inprogress_projects.each do |project| %>
              <%= link_to project.name, bucket_path(project) %>
            <% end %>
        </td>
        <td>
            <% @done_projects.each do |project| %>
              <%= link_to project.name, project_path(project) %>
            <% end %>
        </td>
      </tr>
    </tbody>
  </table>
</div>


  
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>

app/views/projects/new.html.erb
<h1>CREATE NEW PROJECTS</h1>

<%= form_for(@project) do |f| %>
    <%= f.label :name%><br>
    <%= f.text_field :name%><br>
    <br><%= f.label :description%><br>
    <%= f.text_area :description%><br>
    <br><%= f.submit %>
<% end %>

app/views/projects/show.html.erb
<h1><%= @project.name %></h1>
<p><%= @project.description %></p>

<h3>In-progress Tasks</h3>
<ul>
    <% @project.tasks_by_status("In-progress").each do |task| %>
        <li><%= link_to task.name, task_path(task) %></li>
    <% end %>
</ul>

<h3>Done Tasks</h3>
<ul>
    <% @project.tasks_by_status("Done").each do |task| %>
        <li><%= link_to task.name, task_path(task) %></li>
    <% end %>
</ul>

<%= button_to "Edit project", edit_project_path(@project), method: :get %>