config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  resources :tasks
  resources :projects
  root to: 'dashboards#show'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'users/sign_in', to: 'users/sessions#new', as: :new_admin_session
    get 'users/sign_out', to: 'users/sessions#destroy', as: :destroy_admin_session
  end

  # devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManagmentApplication</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
        .flash__alert   { color: red; }
        .flash__notice  { color: blue; }
        .flash__success { color: green; }
    </style>
  </head>

  <body>
    <%= link_to "All Buckets", projects_path%>
    <%= link_to "All Tasks", tasks_path%>
    <%= link_to "Sign in with Google", user_google_oauth2_omniauth_authorize_path %>

    <% if flash.any? %>
      <% flash.each do |key, value| -%>
        <section class="flash flash__<%= key %>"><%= value.html_safe %></section>
      <% end -%>
    <% end %>

    <%= yield %>
  </body>
</html>